apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: platform-project
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.5.1
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/gitops/platform/monitoring/values-prometheus.yaml
    - repoURL: "https://github.com/Abdelhamid108/AtosGraduationProject.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
