# database init, supports mysql too
database=h2
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# Web
spring.thymeleaf.mode=HTML

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
spring.jpa.properties.hibernate.default_batch_fetch_size=16

# Internationalization
spring.messages.basename=messages/messages

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics,threaddump,heapdump
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Prometheus Metrics & Histogram Generation
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.50,0.90,0.95,0.99
management.metrics.distribution.slo.http.server.requests=50ms,100ms,200ms,500ms,1s

# Global Metrics Tags
management.metrics.tags.application=petclinic
management.metrics.tags.environment=${SPRING_PROFILES_ACTIVE:default}

# Limit the maximum number of unique URIs Prometheus will track to 100
management.metrics.web.server.request.max-uri-tags=100

# Logging
logging.level.org.springframework=INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age=12h

# Tell the app to finish processing active requests before shutting down
server.shutdown=graceful
# Give it a max of 30 seconds to finish up (must match your K8s terminationGracePeriodSeconds)
spring.lifecycle.timeout-per-shutdown-phase=30s
