apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform-project # This matches your projects/platform-project.yaml
  source:
    repoURL: "https://github.com/Abdelhamid108/AtosGraduationProject.git"
    targetRevision: main
    path: gitops/platform
    directory:
      recurse: true
      # Include everything in subdirectories, but skip this file itself
      include: "**/*.yaml"
      exclude: "app-platform.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
      - CreateNamespace=true