groups:
  - name: spring-boot-endpoints
    interval: 30s

    rules:

      - record: service:http_latency:p95_5m_by_uri
        expr: |
          histogram_quantile(
            0.95,
            sum(
              rate(
                http_server_requests_seconds_bucket{
                  uri!~"/actuator.*"
                }[5m]
              )
            ) by (le, uri)
          )
