apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Root must be in 'default' project
  source:
    repoURL: "https://github.com/Abdelhamid108/AtosGraduationProject.git"
    targetRevision: main
    path: gitops
    directory:
      recurse: true
      # This tells the root to ONLY manage the projects and the two manager apps
      include: "{projects/*.yaml,platform/app-platform.yaml,workloads/app-workloads.yaml}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true